#!/bin/bash
# //            🇵🇸 FREE PALESTINE 🇵🇸
# //                  🇮🇱 IS 🐷
# // ——————————————————————————————
# // Limit All IP Service by XDXL STORE 🇮🇩
# // My Telegram: t.me/xdxl_store
# // My Channel: t.me/xdx_vpn
# // Telegram Group: t.me/vpn_storeid
# // ——————————————————————————————

function vmip(){
echo -n > /var/log/xray/access.log
data=( `ls /etc/xray/limit/vmess/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/xray/limit/vmess/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvmess.txt | wc -l )
                  echo "resvm $user" | at now + 15 minutes > /dev/null
                  systemctl restart xray
function log_vm(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>  ⚠️ NOTIF MULTI LOGIN XRAY VMESS⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Login IP : </code><code>$cekcek</code>
<code>Limit IP : </code><code>$iplimit</code>
<code>────────────────────</code>
<code>Account Locked selama 15 menit</code>
<code>────────────────────</code>
"'&reply_markup={"inline_keyboard":[[{"text":" ⛈️ ɢʀᴏᴜᴘ ⛈️ ","url":"https://t.me/vpn_storeid"}]]}' 
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
log_vm
                  else
            echo ""
        fi
        sleep 0.1
    done
}
function vlip(){
echo -n > /var/log/xray/access.log
data=( `ls /etc/xray/limit/vless/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/xray/limit/vless/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvless.txt | wc -l)
                  echo "resvl $user" | at now + 15 minutes > /dev/null
                  systemctl restart xray
function log_vl(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>  ⚠️ NOTIF MULTI LOGIN XRAY VLESS⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Login IP : </code><code>$cekcek</code>
<code>Limit IP : </code><code>$iplimit</code>
l<code>────────────────────</code>
<code>Account Locked selama 15 menit</code>
<code>────────────────────</code>
"'&reply_markup={"inline_keyboard":[[{"text":" ⛈️ ɢʀᴏᴜᴘ ⛈️ ","url":"https://t.me/vpn_storeid"}]]}' 
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
log_vl
                else
            echo ""
        fi
        sleep 0.1
    done
}
function trip(){
echo -n > /var/log/xray/access.log
data=( `ls /etc/xray/limit/trojan/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/xray/limit/trojan/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/iptrojan.txt | wc -l)
                  echo "restr $user" | at now + 15 minutes > /dev/null
                  systemctl restart xray
function log_tr(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>  ⚠️ NOTIF MULTI LOGIN TROJAN ⚠️</b>
<code>────────────────────</code>
<code>Username : </code><code>$user</code>
<code>Login IP : </code><code>$cekcek</code>
<code>Limit IP : </code><code>$iplimit</code>
<code>────────────────────</code>
<code>Account Locked selama 15 menit</code>
<code>────────────────────</code>
"'&reply_markup={"inline_keyboard":[[{"text":" ⛈️ ɢʀᴏᴜᴘ ⛈️ ","url":"https://t.me/vpn_storeid"}]]}' 
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
log_tr
                else
            echo ""
        fi
        sleep 0.1
    done
}

function ssh_ip() {
function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN SSH ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Limit IP  : </code><code>$iplimit</code>
<code>Login IP  : </code><code>$cekcek</code>
<code>────────────────────</code>
<code>Account Locked 15 minutes</code>
<code>────────────────────</code>
"'&reply_markup={"inline_keyboard":[[{"text":" ⛈️ ɢʀᴏᴜᴘ ⛈️ ","url":"https://t.me/vpn_storeid"}]]}' 
curl -s --max-time 10 -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
mulog=$(fvssh)
data=( `ls /etc/xray/limit/ssh/ip`);
for user in "${data[@]}"
do
iplimit=$(cat /etc/xray/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
egrep "^$user" /etc/passwd >/dev/null
passwd -l $user
systemctl restart ws-epro
send_log
echo "passwd -u $user" | at now + 15 minutes > /dev/null
systemctl restart ws-epro
else
echo > /dev/null
fi
sleep 0.1
done
}

if [[ ${1} == "vmip" ]]; then
vmip
elif [[ ${1} == "vlip" ]]; then
vlip
elif [[ ${1} == "trip" ]]; then
trip
elif [[ ${1} == "ssh_ip" ]]; then
ssh_ip
fi
